### ISSUE TITLE
Cadastro de vereadores não está funcionando.

### ISSUE THREAD

**Issue by wab030** [Minhacps/VotaCampinas#11]
Quando cadastro um vereador consigo responder as prioridades mas quando clico no botão enviar o sistema fica parado. No banco o sistema cadastrou a opção da prioridade 1 e da 2 mas da 3 não.

**Comment by victorperin** [comment]
Estranho, vou dar uma verificada aqui.

**Comment by victorperin** [comment]
Percebi que o erro ocorre quando um objeto não padronizado é enviado para a api. Vou travar isso na api, mas ainda precisa que alguém corrija no front.

**Comment by gabriel-ribeiro-ir** [comment]
Como é o json q tem q ser enviado @victorperin? passa ae que eu corrijo

**Comment by wab030** [comment]
@victorperin @gabriel-ribeiro-ir O cadastro funciona no banco de dados local mas não funciona quando uso o sistema via votacampinas.org.br

**Comment by gabriel-ribeiro-ir** [comment]
@wab030 aqui o cadastro também funciona. Imagino que o deploy ainda não foi feito.
@victormiguez o deploy automatico já ta rolando?

**Comment by wab030** [comment]
@gabriel-ribeiro-ir Mas faltava o @victorperin te passar algo para fazer no front não faltava?

**Comment by gabriel-ribeiro-ir** [comment]
Então, na verdade acho que era uma correção que ele precisava fazer. Eu teste aqui e também foi normal. Vamos esperar ele responder.

**Comment by wab030** [comment]
OK. Localmente aqui funciona também. Só a versão que está na hospedagem não funciona.

**Comment by gabriel-ribeiro-ir** [comment]
@wab030 sobre isso é que ainda falta fazer o deploy para lá

**Comment by wab030** [comment]
Bom dia @gabriel-ribeiro-ir bom dia @victorperin Esse deploy já deveria estar integrado na última release? Digo isso pois ontem o Miguez fez o deploy mas o problema ainda persiste. O vereador consegue responder as prioridades mas não consegue enviar. Um abraço.

**Comment by wab030** [comment]
Apagamos o banco ontem e agora está funcionando. Valeu
