### ISSUE TITLE
Criar uma tabela com os partidos polítcos do Brasil. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/VotaCampinas#13]
Criar uma tabela com os partidos políticos do Brasil para que o candidato selecione em uma dropdown list. Não é necessário criar uma página para cadastro dos partidos. Todos os partidos do Brasil são esses aqui: http://www.tse.jus.br/partidos/partidos-politicos/registrados-no-tse

O cadastro poderia ter número, sigla e nome. No dropdown pode aparecer somente a sigla.

**Comment by victormiguez** [comment]
Criei um JSON com os partidos.
Chegando em casa faço um seed pro banco de dados e implemento a busca no cadastro 👍

**Comment by victormiguez** [comment]
Inseri a tabela dos partidos e fiz o relacionamento com o vereador no cadastro.
Removi os dois cadastros dos vereadores que estavam no banco de produção, só para garantir que não tenha problema com os dados.
Qualquer coisa, me avise!
