### ISSUE TITLE
Ranking não está aparecendo. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/VotaCampinas#17]
Testando o cadastro localmente consegui cadastrar 2 vereadores e 2 eleitores mas o ranking não está aparecendo.

**Comment by gabriel-ribeiro-ir** [comment]
@wab030 as perguntas foram respondidas também?

**Comment by wab030** [comment]
Sim.

**Comment by gabriel-ribeiro-ir** [comment]
@wab030  Subi uma alteração pra fazer funcionar. Não aparece o nome do partido ainda, mas pelo menos da pra vc testar. 
@victormiguez @victorperin mudei no commit https://github.com/Minhacps/VotaCampinas/commit/849f67e88e4f46925053d94ab922acd3a8428bab

**Comment by wab030** [comment]
@gabriel-ribeiro-ir Testei e funcionou.
