### ISSUE TITLE
Pagina de Login não informa mensagem de erro

### ISSUE THREAD

**Issue by dsoldera** [Minhacps/VotaCampinas#18]
Olá,

Estou tentando fazer login com um usuário que não existe e não informa nenhuma mensagem de Erro para o usuário.

**Comment by gabriel-ribeiro-ir** [comment]
@dsoldera não temos mensagem de erro em momento nenhum no sistema, pelo menos por enquanto.

**Comment by victormiguez** [comment]
Puts, verdade, ficou faltando isso. :/
Pode deixar essa issue comigo!
