### ISSUE TITLE
Perguntas perdendo a memória. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/VotaCampinas#20]
Quando o eleitor responde as perguntas e clica no botão voltar as respostas anteriores são perdidas.

**Comment by gabriel-ribeiro-ir** [comment]
@wab030 veja se ocorre, testei aqui e está ok. O @victormiguez comentou comigo que corrigiu isso há uns commits atras.

**Comment by wab030** [comment]
Perfeito. Funcionando. Valeu.
