### ISSUE TITLE
Índice de afinidade está aparecendo 0% para todos os candidatos. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/VotaCampinas#21]
O índice de afinidade está aparecendo como 0% para todos os candidatos. Já existem 2 vereadores cadastrados para vcs fazerem os testes. anexo tela. 
![screenshot from 2016-08-18 09-26-15](https://cloud.githubusercontent.com/assets/7780073/17773719/19f9cfc2-6526-11e6-995f-719f30deda10.png)

**Comment by victormiguez** [comment]
Chegando em casa vejo o que está rolando.

**Comment by victormiguez** [comment]
Resolvido no commit [e596f8f](https://github.com/Minhacps/VotaCampinas/commit/e596f8fcba957c98befacfe34cdd09a5aac87965).
@wab030, pode verificar se está ok?

**Comment by wab030** [comment]
@victormiguez Perfeito.
