### ISSUE TITLE
Não estão aparecendo todos os candidatos a vereador na página de ranking.

### ISSUE THREAD

**Issue by wab030** [Minhacps/VotaCampinas#34]
Um exemplo é o usuário userid=30 Lê Firmino. 
Outros exemplos @victorperin 
Danilo Sanches
Amara Moira

**Comment by victormiguez** [comment]
@wab030 dei uma verificada no banco, tem alguns registros estranhos, na tabela de usuários tem 40 registros de vereadores, mas na de vereadores apenas 29. No caso do Danilo Sanches, ele está registrado sem um partido, por isso não está aparecendo. Infelizmente agora não consegui identificar o que está causando isso.
Não sei se a única alternativa nesses casos é recadastrar esses candidatos. Vou correr atrás disso.

**Comment by victormiguez** [comment]
Como já identificamos que o problema era com o id dos partidos, vou fechar essa issue, beleza @wab030?

**Comment by wab030** [comment]
Beleza.

Em 3 de set de 2016 11:54 AM, "Victor Miguez" <notifications@github.com>
escreveu:
