### ISSUE TITLE
Erro ao criar conta

### ISSUE THREAD

**Issue by victormiguez** [Minhacps/VotaCampinas#42]
Em alguns cadastros o servidor retorna um erro 500, e mesmo assim o cadastro é feito com sucesso.
Mensagem de erro:
```
{"err":{"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read","fatal":true}}
```

**Comment by victorperin** [comment]
Então isso aqui foi finalizado, certo?
Vou fechar a issue, se reocorrer, só abrir de novo.
