### ISSUE TITLE
Para alguns candidatos as respostas no perfil não aparecem corretamente. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/VotaCampinas#48]
Provavelmente são candidatos que por algum motivo tem respostas repetidas no banco de respostas das perguntas.

**Comment by victorperin** [comment]
@wab030 pode me dar um exemplo? Me mande por DM no Slack e se possível. Vou precisar da string de conexão com o banco também.

**Comment by victorperin** [comment]
Percebi que algumas vezes, na tela de detalhes do candidato, as vezes as respostas dele ficam em branco.
Verifiquei e parece que a api retorna valores normalmente.

**Comment by victorperin** [comment]
removi todas as repostas de vereadores e usuarios duplicadas. Mantive a ultima escolha de cada um.
Também adicionei uma chave unique para o id do usuário e id da pergunta. Agora não é possivel duplicar.

Em teoria, tudo é para ficar normal, mas é bom sempre ficar atento.
