### ISSUE TITLE
Ranking está errando no calculo das prioridades.

### ISSUE THREAD

**Issue by victorperin** [Minhacps/VotaCampinas#51]

**Comment by victormiguez** [comment]
@victorperin você tem mais informações sobre isso? Como descobriu que está errando no cálculo?

**Comment by victorperin** [comment]
Descobri depois que o @wab030 falou que o mesmo usuario, comparado com ele mesmo dava 97% de afinidade. Deve ter algum erro, talvez a ultima ou a primeira comparação.

**Comment by victormiguez** [comment]
Cara, isso era um erro de front, o cálculo de porcentagem estava considerando uma questão que não existe, e foi corrigido aqui fcf67f8.
Considerando isso, acho que não há erro no back-end.

**Comment by wab030** [comment]
@victorperin @victormiguez O problema ainda continua acontecendo.

**Comment by victorperin** [comment]
Desculpe, preferi remover para termos problemas. Lembre-se que como essa pagina qualquer pessoa pode acessar...

**Comment by victorperin** [comment]
Corrigido. :smile:
