### ISSUE TITLE
Incluir o seguinte texto no footer com letras pequenas e centralizado. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/VotaCampinas#7]
Vota Campinas é uma plataforma aberta e baseada em software livre os realizadores não se responsabilizam pelas informações fornecidas pelos candidatos, nem pelo comportamento deles durante o período eleitoral, e se eleitos, durante seus respectivos mandatos.

Este projeto é distribuido sob a licença Affero General Public License.

**Comment by guiluchesi** [comment]
Corrigido
